### ISSUE TITLE
Ask for data release

### ISSUE THREAD

**Issue by DorisxinDU** [diegodoimo/hierarchical_nucleation#1]
Thanks for your wonderful results and I am trying to learning it as a researcher for my work based on information theory. I tried to run your code but it shows the distance file is not available any more. Please can you try to release it again and I am happy to have cooperation if you are interested in information theory based explanation of AI.  Thanks very much for your help.

**Comment by DorisxinDU** [comment]
@AldoGl @diegodoimo

**Comment by diegodoimo** [comment]
Sure! I apologize for the inconvenience. I'll take care of this in the next few days.

**Comment by diegodoimo** [comment]
[DorisxinDU](https://github.com/DorisxinDU)  I included in the jupyter notebook the link that should allow you to download the data. You should reinstall the repository since I modified the environment slightly. Tell me if you manage to make it work. 

I also would like to tell you that we have developed a library, [DADApy](https://github.com/sissa-data-science/DADApy), that implements the tools we used in this paper, i.e. density peak clustering and neighborhood overlap. You can try to have a look at it.
